### ISSUE TITLE
Home Assistant plugin not working on OPNsense 24.7

### ISSUE THREAD

**Issue by kbhsn4** [mimugmail/opn-repo#227]
The new system OPNsense widget seems to cause problems with the plugin:

```
[26-Jul-2024 10:08:01 Europe/Copenhagen] PHP Fatal error:  Uncaught Error: Failed opening required '/usr/local/www/widgets/api/plugins/system.inc' (include_path='/usr/local/etc/inc:/usr/local/www:/usr/local/opnsense/mvc:/usr/local/opnsense/contrib:/usr/local/share/pear:/usr/local/share') in /usr/local/etc/inc/xmlrpc/hass.inc(12) : eval()'d code:5
Stack trace:
#0 /usr/local/etc/inc/xmlrpc/hass.inc(12): eval()
#1 /usr/local/opnsense/contrib/IXR/IXR_Library.php(446): exec_php_xmlrpc('\nini_set('displ...')
#2 /usr/local/opnsense/contrib/IXR/IXR_Library.php(384): IXR_Server->call('opnsense.exec_p...', '\nini_set('displ...')
#3 /usr/local/opnsense/contrib/IXR/IXR_Library.php(357): IXR_Server->serve('<?xml version='...')
#4 /usr/local/etc/inc/xmlrpc.inc(67): IXR_Server->__construct(Array)
#5 /usr/local/www/xmlrpc.php(104): XMLRPCServer->start()
#6 {main}
  thrown in /usr/local/etc/inc/xmlrpc/hass.inc(12) : eval()'d code on line 5
```

**Comment by nima-1102** [comment]
Same problem here, the plug-in crashes in opnsense after the 24.7 update.

**Comment by DaVinylSmith** [comment]
+1 here. haven't tried uninstalling & reinstalling yet though

**Comment by mimugmail** [comment]
I'm not the author of the plugin, just hosting it. Maybe you want to ask over there?

**Comment by kbhsn4** [comment]
> I'm not the author of the plugin, just hosting it. Maybe you want to ask over there?

Oh, sorry - I thought the logic was in the OPNsense part, I see now that the code gets pushed from the Home Assistant plugin. There's already an [open issue](https://github.com/travisghansen/hass-opnsense/issues/143) on the HASS plugin about the problem.
